### ISSUE TITLE
Update CSGO Broke Plugin

### ISSUE THREAD

**Issue by crashzk** [JDW1337/AntiDLL#15]
It is showing the following error:
```
L 02/03/2023 - 16:38:04: [AntiDLL] Sigscan for Signature failed
L 02/03/2023 - 16:38:04: [SM] Unable to load extension "AntiDLL.ext": Failed to create interceptor
```

**Comment by stefanx111** [comment]
Check with this

"Games"
{
    "#default"
    {
        "Signatures"
        {
            "Signature"
            {
                "library" "engine"
                "linux"   "\x55\x89\xE5\x57\x56\x53\x81\xEC\x3C\x0A\x00\x00"        
                "windows" "\x55\x8B\xEC\x83\xE4\xF8\x83\xEC\x48\x56\x57\xC7\x44\x24\x0C\x00\x00\x00\x00"
            }
        }
    }
}

**Comment by crashzk** [comment]
@stefanx111 thanks.

PR #16
